
services:
  db:
    image: postgres:16-alpine
    restart: always
    ports:
      - "9002:9002"
    environment:
      POSTGRES_USER: 
      POSTGRES_PASSWORD: 
      POSTGRES_DB: 
      PGPORT: 9002
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  server:
    build: ./server
    ports:
      - "9001:9001"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ./.env

  client:
    build: ./client
    ports:
      - "9000:9000"
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    env_file:
      - ./.env
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true

volumes:
  pgdata:
