FROM node:18-alpine

# Create app directory
WORKDIR /usr/src/app

# Install app dependencies
COPY package*.json ./
RUN npm ci --only=production

# Copy app source
COPY . .

# Add non-root user
RUN addgroup -g 1001 -S nodejs && adduser -S nodejs -G nodejs -u 1001
USER nodejs

# Run as non-root user
EXPOSE 5000
CMD ["node", "server.js"]